using System;
using System.Collections.Generic;
using System.Linq;
using Content.Client.Guidebook.Controls;
using Content.Client.UserInterface.ControlExtensions;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._HorizonNova.Humanoid;

/// <summary>
/// Horizon Nova: list of markings belonging to a single marking layer.
/// Port of the Wega layer marking picker (Content.Client/Humanoid/LayerMarkingPicker.xaml.cs),
/// with layers mapped onto <see cref="MarkingLayerEntry"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LayerMarkingPicker : BoxContainer
{
    private readonly MarkingLayerEntry _entry;
    private readonly MarkingsViewModel _markingsModel;
    private List<ISearchableControl> _searchable = new();
    private const int ColumnWidth = 500;

    public LayerMarkingPicker(MarkingsViewModel markingsModel, MarkingLayerEntry entry)
    {
        RobustXamlLoader.Load(this);

        _markingsModel = markingsModel;
        _entry = entry;

        OrderingItems.AddChild(new LayerMarkingOrderer(markingsModel, entry));

        UpdateMarkings();

        SearchBar.OnTextChanged += _ =>
        {
            foreach (var element in _searchable)
            {
                element.SetHiddenState(true, SearchBar.Text.Trim());
            }
        };

        UpdateCount();

        ReorderButton.OnPressed += ReorderButtonPressed;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.MarkingsReset += UpdateCount;
        _markingsModel.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.MarkingsReset -= UpdateCount;
        _markingsModel.MarkingsChanged -= MarkingsChanged;
    }

    private void MarkingsChanged(MarkingCategories category, MarkingChangeType type)
    {
        if (_entry.Category != category)
            return;

        UpdateCount();
    }

    private void UpdateMarkings()
    {
        var available = _markingsModel.GetAvailable(_entry.Category, _entry.BodyParts);

        foreach (var marking in available.Values.OrderBy(GetMarkingName))
        {
            var item = new LayerMarkingItem(_markingsModel, _entry.Category, marking, true);
            Items.AddChild(item);
        }

        _searchable = Items.GetSearchableControls();
    }

    private void UpdateCount()
    {
        _markingsModel.GetMarkingCounts(_entry.Category, _entry.BodyParts, out var isRequired, out var count, out var selected);

        if (count < 0)
        {
            MarkingsStatus.Visible = false;
            MarkingsStatus.Text = string.Empty;
            return;
        }

        MarkingsStatus.Visible = true;
        MarkingsStatus.Text = Loc.GetString("markings-limits",
            ("required", isRequired),
            ("count", count),
            ("selectable", count - selected));
    }

    private void ReorderButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (ReorderButton.Pressed)
        {
            SelectionItems.Visible = false;
            SearchBar.Visible = false;
            OrderingItems.Visible = true;
        }
        else
        {
            SelectionItems.Visible = true;
            SearchBar.Visible = true;
            OrderingItems.Visible = false;
        }
    }

    protected override void Resized()
    {
        base.Resized();

        Items.Columns = Math.Max(1, (int) (Width / ColumnWidth));
    }

    private static string GetMarkingName(MarkingPrototype marking)
    {
        return Loc.TryGetString($"marking-{marking.ID}", out var name) ? name : marking.ID;
    }
}
