using System;
using System.Linq;
using Content.Client.Guidebook.Controls;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Utility;

namespace Content.Client._HorizonNova.Humanoid;

/// <summary>
/// Horizon Nova: a single marking row in the markings picker.
/// Port of the Wega layer marking item (Content.Client/Humanoid/LayerMarkingItem.xaml.cs),
/// with the organ concept replaced by a marking category.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LayerMarkingItem : BoxContainer, ISearchableControl
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private readonly SpriteSystem _sprite;

    private readonly MarkingsViewModel _markingsModel;
    private readonly MarkingPrototype _markingPrototype;
    private readonly MarkingCategories _category;
    private readonly bool _interactive;

    private List<ColorSelectorSliders>? _colorSliders;

    public event Action<GUIBoundKeyEventArgs, LayerMarkingItem>? Pressed;
    public event Action<GUIBoundKeyEventArgs, LayerMarkingItem>? Unpressed;

    public string MarkingId => _markingPrototype.ID;

    public LayerMarkingItem(MarkingsViewModel model, MarkingCategories category, MarkingPrototype prototype, bool interactive)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        _markingsModel = model;
        _markingPrototype = prototype;
        _category = category;
        _interactive = interactive;

        UpdateData();
        UpdateSelection();

        SelectButton.OnPressed += SelectButtonPressed;
        ColorsButton.OnPressed += ColorsButtonPressed;

        OnKeyBindDown += OnPressed;
        OnKeyBindUp += OnUnpressed;

        if (!interactive)
        {
            SelectButton.MouseFilter = Control.MouseFilterMode.Ignore;
        }
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.MarkingsReset += UpdateSelection;
        _markingsModel.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.MarkingsReset -= UpdateSelection;
        _markingsModel.MarkingsChanged -= MarkingsChanged;
    }

    private void MarkingsChanged(MarkingCategories category, MarkingChangeType type)
    {
        if (_category != category)
            return;

        UpdateSelection();
    }

    private void UpdateData()
    {
        MarkingTexture.Textures = _markingPrototype.Sprites.Select(layer => _sprite.Frame0(layer)).ToList();
        SelectButton.Text = GetMarkingName(_markingPrototype);
    }

    private void UpdateSelection()
    {
        var selected = _markingsModel.IsMarkingSelected(_category, _markingPrototype.ID);
        SelectButton.Pressed = selected && _interactive;
        ColorsButton.Visible = selected && _interactive && _markingsModel.IsMarkingColorCustomizable(_category, _markingPrototype.ID);

        if (!selected || !_interactive)
        {
            ColorsButton.Pressed = false;
            ColorsContainer.Visible = false;
        }

        if (_markingsModel.GetMarking(_category, _markingPrototype.ID) is { } marking &&
            _colorSliders is { } sliders)
        {
            for (var i = 0; i < sliders.Count && i < marking.MarkingColors.Count; i++)
            {
                sliders[i].Color = marking.MarkingColors[i];
            }
        }
    }

    private void SelectButtonPressed(BaseButton.ButtonEventArgs args)
    {
        if (!_interactive)
        {
            SelectButton.Pressed = false;
            return;
        }

        if (_markingsModel.IsMarkingSelected(_category, _markingPrototype.ID))
        {
            if (!_markingsModel.TryDeselectMarking(_category, _markingPrototype.ID))
            {
                SelectButton.Pressed = true;
            }
        }
        else
        {
            if (!_markingsModel.TrySelectMarking(_category, _markingPrototype.ID))
            {
                SelectButton.Pressed = false;
            }
        }
    }

    private void ColorsButtonPressed(BaseButton.ButtonEventArgs args)
    {
        ColorsContainer.Visible = ColorsButton.Pressed;

        if (_colorSliders is not null)
            return;

        if (_markingsModel.GetMarking(_category, _markingPrototype.ID) is not { } marking)
            return;

        _colorSliders = new();

        for (var i = 0; i < _markingPrototype.Sprites.Count; i++)
        {
            var container = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                HorizontalExpand = true,
            };

            ColorsContainer.AddChild(container);

            var selector = new ColorSelectorSliders
            {
                SelectorType = ColorSelectorSliders.ColorSelectorType.Hsv,
            };

            var label = _markingPrototype.Sprites[i] switch
            {
                SpriteSpecifier.Rsi rsi => GetMarkingStateName(_markingPrototype.ID, rsi.RsiState),
                SpriteSpecifier.Texture texture => GetMarkingStateName(_markingPrototype.ID, texture.TexturePath.Filename),
                _ => _markingPrototype.ID,
            };

            container.AddChild(new Label { Text = label });
            container.AddChild(selector);

            selector.Color = i < marking.MarkingColors.Count ? marking.MarkingColors[i] : Color.White;

            _colorSliders.Add(selector);

            var colorIndex = i;
            selector.OnColorChanged += _ =>
            {
                _markingsModel.TrySetMarkingColor(_category, _markingPrototype.ID, colorIndex, selector.Color);
            };
        }
    }

    public bool CheckMatchesSearch(string query)
    {
        return GetMarkingName(_markingPrototype).Contains(query, StringComparison.OrdinalIgnoreCase);
    }

    public void SetHiddenState(bool state, string query)
    {
        Visible = CheckMatchesSearch(query) ? state : !state;
    }

    private void OnPressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Pressed?.Invoke(args, this);
    }

    private void OnUnpressed(GUIBoundKeyEventArgs args)
    {
        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        Unpressed?.Invoke(args, this);
    }

    private static string GetMarkingName(MarkingPrototype marking)
    {
        return Loc.TryGetString($"marking-{marking.ID}", out var name) ? name : marking.ID;
    }

    private static string GetMarkingStateName(string markingId, string state)
    {
        return Loc.TryGetString($"marking-{markingId}-{state}", out var name) ? name : $"{markingId}-{state}";
    }
}
