using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using Content.Client.Interaction;
using Content.Shared.Humanoid.Markings;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client._HorizonNova.Humanoid;

/// <summary>
/// Horizon Nova: drag and drop reordering of the selected markings in a layer.
/// Port of the Wega layer marking orderer (Content.Client/Humanoid/LayerMarkingOrderer.xaml.cs),
/// with layers mapped onto <see cref="MarkingLayerEntry"/>. The drop target style is applied
/// directly through <see cref="StyleBoxFlat"/> because Horizon Nova does not ship the newer
/// style class sheetlets used by Wega.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class LayerMarkingOrderer : BoxContainer
{
    private readonly MarkingLayerEntry _entry;
    private readonly MarkingsViewModel _markingsModel;
    private readonly DragDropHelper<LayerMarkingDragged> _dragDropHelper;
    private readonly List<LayerDragDropBeacon> _beacons = new();
    private LayerDragDropBeacon? _dragTarget;

    [Dependency] private readonly IPrototypeManager _prototype = default!;

    public LayerMarkingOrderer(MarkingsViewModel markingsModel, MarkingLayerEntry entry)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _markingsModel = markingsModel;
        _entry = entry;
        _dragDropHelper = new DragDropHelper<LayerMarkingDragged>(OnBeginDrag, OnContinueDrag, OnEndDrag);

        UpdateItems();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();

        _markingsModel.MarkingsReset += UpdateItems;
        _markingsModel.MarkingsChanged += MarkingsChanged;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        _markingsModel.MarkingsReset -= UpdateItems;
        _markingsModel.MarkingsChanged -= MarkingsChanged;
    }

    private void MarkingsChanged(MarkingCategories category, MarkingChangeType type)
    {
        if (_entry.Category != category)
            return;

        UpdateItems();
    }

    private void UpdateItems()
    {
        Items.RemoveAllChildren();
        _beacons.Clear();

        if (_markingsModel.SelectedMarkings(_entry.Category, _entry.BodyParts) is not { } markings)
            return;

        for (var idx = 0; idx < markings.Count; idx++)
        {
            var marking = markings[idx];

            if (!_prototype.TryIndex<MarkingPrototype>(marking.MarkingId, out var prototype))
                continue;

            var container = new LayerMarkingItemContainer
            {
                Margin = new Thickness(4),
            };

            var item = new LayerMarkingItem(_markingsModel, _entry.Category, prototype, false)
            {
                DefaultCursorShape = CursorShape.Hand,
            };
            item.Pressed += (args, control) => OnItemPressed(args, control, container);
            item.Unpressed += OnItemUnpressed;

            container.AddChild(item);

            var before = new LayerDragDropBeacon(CandidatePosition.Before, idx);
            var after = new LayerDragDropBeacon(CandidatePosition.After, idx);
            _beacons.Add(before);
            _beacons.Add(after);

            Items.AddChild(before);
            Items.AddChild(container);
            Items.AddChild(after);
        }
    }

    private void OnItemPressed(GUIBoundKeyEventArgs args, LayerMarkingItem control, LayerMarkingItemContainer container)
    {
        _dragDropHelper.MouseDown(new LayerMarkingDragged(control, container));
    }

    private void OnItemUnpressed(GUIBoundKeyEventArgs args, LayerMarkingItem control)
    {
        _dragDropHelper.EndDrag();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        _dragDropHelper.Update(args.DeltaSeconds);
    }

    private bool OnBeginDrag()
    {
        var (item, container) = _dragDropHelper.Dragged;

        container.Visible = false;
        item.Orphan();
        item.DefaultCursorShape = CursorShape.Move;
        UserInterfaceManager.PopupRoot.AddChild(item);
        LayoutContainer.SetPosition(item, UserInterfaceManager.MousePositionScaled.Position - new Vector2(32, 32));
        return true;
    }

    private bool OnContinueDrag(float frameTime)
    {
        var (item, _) = _dragDropHelper.Dragged;

        LayoutContainer.SetPosition(item, UserInterfaceManager.MousePositionScaled.Position - new Vector2(32, 32));

        var closestBeacon = _beacons.MinBy(beacon =>
            (UserInterfaceManager.MousePositionScaled.Position - beacon.GlobalPosition).LengthSquared());

        if (closestBeacon != _dragTarget)
        {
            _dragTarget?.UnbecomeTarget();
            _dragTarget = closestBeacon;
            _dragTarget?.BecomeTarget();
        }

        return true;
    }

    private void OnEndDrag()
    {
        var (item, container) = _dragDropHelper.Dragged;

        container.Visible = true;
        item.Orphan();
        container.AddChild(item);
        _dragTarget?.UnbecomeTarget();

        if (_dragTarget != null)
        {
            _markingsModel.ChangeMarkingOrder(_entry.Category, _entry.BodyParts, item.MarkingId, _dragTarget.CandidatePosition, _dragTarget.Index);
        }
    }
}

internal readonly record struct LayerMarkingDragged(LayerMarkingItem Item, LayerMarkingItemContainer Container);

internal sealed class LayerMarkingItemContainer : PanelContainer
{
    public LayerMarkingItemContainer()
    {
        SetHeight = 64;
        HorizontalExpand = true;
    }
}

internal sealed class LayerDragDropBeacon : PanelContainer
{
    private static readonly StyleBoxFlat TargetStyle = new()
    {
        BackgroundColor = Color.FromHex("#FFFFFF22"),
        BorderColor = Color.FromHex("#FFFFFF88"),
        BorderThickness = new Thickness(1),
    };

    public readonly CandidatePosition CandidatePosition;
    public readonly int Index;

    public LayerDragDropBeacon(CandidatePosition position, int index)
    {
        CandidatePosition = position;
        Index = index;
    }

    public void BecomeTarget()
    {
        SetHeight = 64;
        HorizontalExpand = true;
        PanelOverride = TargetStyle;
    }

    public void UnbecomeTarget()
    {
        SetHeight = float.NaN;
        PanelOverride = null;
    }
}
