using System;
using System.Collections.Generic;
using System.Linq;
using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Markings;
using Content.Shared.Humanoid.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._HorizonNova.Humanoid;

/// <summary>
/// Horizon Nova: the "appearance features" (markings) picker used in the character editor.
/// Port of the Wega markings picker interface (Content.Client/Humanoid/MarkingPicker.cs and
/// related controls). The organ tabs are mapped onto <see cref="MarkingRegion"/> and the layer
/// tabs onto <see cref="MarkingLayerEntry"/>.
/// </summary>
[GenerateTypedNameReferences]
public sealed partial class MarkingsPicker : Control
{
    [Dependency] private readonly MarkingManager _markingManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    private readonly MarkingsViewModel _model = new();

    public Action<MarkingSet>? OnMarkingAdded;
    public Action<MarkingSet>? OnMarkingRemoved;
    public Action<MarkingSet>? OnMarkingColorChange;
    public Action<MarkingSet>? OnMarkingRankChange;

    private string _species = SharedHumanoidAppearanceSystem.DefaultSpecies;
    private Sex _sex = Sex.Male;
    private Color _skinColor = Color.White;
    private Color _eyeColor = Color.Black;

    private readonly HashSet<MarkingCategories> _ignoredCategories = new();
    private string _ignoreCategories = string.Empty;
    private bool _ignoreSpecies;
    private bool _forced;
    private bool _ready;

    public Color CurrentSkinColor
    {
        get => _skinColor;
        set
        {
            _skinColor = value;
            _model.SkinColor = value;
        }
    }

    public Color CurrentEyeColor
    {
        get => _eyeColor;
        set
        {
            _eyeColor = value;
            _model.EyeColor = value;
        }
    }

    // Kept for API compatibility with the previous markings picker. Hair and facial hair
    // are edited through the dedicated single marking pickers, so these are unused here.
    public Marking? HairMarking;
    public Marking? FacialHairMarking;

    public string IgnoreCategories
    {
        get => _ignoreCategories;
        set
        {
            _ignoreCategories = value;
            RebuildIgnoredCategories();
            if (_ready)
                Refresh();
        }
    }

    public bool Forced
    {
        get => _forced;
        set
        {
            _forced = value;
            _model.Forced = value;
        }
    }

    public bool IgnoreSpecies
    {
        get => _ignoreSpecies;
        set
        {
            _ignoreSpecies = value;
            _model.EnforceSpeciesAndSex = !value;
            if (_ready)
                Refresh();
        }
    }

    public MarkingsPicker()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _model.MarkingsChanged += OnModelMarkingsChanged;
        _ready = true;
        Refresh();
    }

    /// <summary>
    /// Sets the markings and all context needed to validate and color them.
    /// </summary>
    public void SetData(List<Marking> newMarkings, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        var pointsProto = _prototypeManager.Index<SpeciesPrototype>(species).MarkingPoints;
        var set = new MarkingSet(newMarkings, pointsProto, _markingManager, _prototypeManager);
        SetData(set, species, sex, skinColor, eyeColor);
    }

    public void SetData(MarkingSet set, string species, Sex sex, Color skinColor, Color eyeColor)
    {
        _species = species;
        _sex = sex;
        _skinColor = skinColor;
        _eyeColor = eyeColor;

        _model.Species = species;
        _model.Sex = sex;
        _model.SkinColor = skinColor;
        _model.EyeColor = eyeColor;

        if (!_ignoreSpecies)
            set.EnsureSpecies(species, skinColor, _markingManager, _prototypeManager);

        _model.Markings = set;
        Refresh();
    }

    public void SetSkinColor(Color color) => CurrentSkinColor = color;

    public void SetEyeColor(Color color) => CurrentEyeColor = color;

    // Repopulate in case markings are restricted and filter out invalid ones,
    // while preserving the markings that are still valid.
    public void SetSpecies(string species)
    {
        var markingList = _model.Markings.GetForwardEnumerator().ToList();
        var pointsProto = _prototypeManager.Index<SpeciesPrototype>(species).MarkingPoints;
        var set = new MarkingSet(markingList, pointsProto, _markingManager, _prototypeManager);
        SetData(set, species, _sex, _skinColor, _eyeColor);
    }

    public void SetSex(Sex sex)
    {
        var markingList = _model.Markings.GetForwardEnumerator().ToList();
        var pointsProto = _prototypeManager.Index<SpeciesPrototype>(_species).MarkingPoints;
        var set = new MarkingSet(markingList, pointsProto, _markingManager, _prototypeManager);
        SetData(set, _species, sex, _skinColor, _eyeColor);
    }

    /// <summary>
    /// Kept for API compatibility. The ported interface rebuilds itself on demand, so this is a no-op.
    /// </summary>
    public void Populate(string filter)
    {
    }

    /// <summary>
    /// Kept for API compatibility. The ported interface rebuilds itself on demand, so this is a no-op.
    /// </summary>
    public void PopulateUsed()
    {
    }

    private void OnModelMarkingsChanged(MarkingCategories category, MarkingChangeType type)
    {
        switch (type)
        {
            case MarkingChangeType.Added:
                OnMarkingAdded?.Invoke(_model.Markings);
                break;
            case MarkingChangeType.Removed:
                OnMarkingRemoved?.Invoke(_model.Markings);
                break;
            case MarkingChangeType.Color:
                OnMarkingColorChange?.Invoke(_model.Markings);
                break;
            case MarkingChangeType.Rank:
                OnMarkingRankChange?.Invoke(_model.Markings);
                break;
        }
    }

    private void Refresh()
    {
        if (CategoryTabs == null)
            return;

        _model.OrganData = BuildOrganData();

        CategoryTabs.RemoveAllChildren();

        var index = 0;
        foreach (var region in RegionOrder)
        {
            if (!_model.OrganData.TryGetValue(region, out var layers))
                continue;

            var control = new OrganMarkingPicker(_model, region, layers);
            if (control.Empty)
                continue;

            CategoryTabs.AddChild(control);
            CategoryTabs.SetTabTitle(index, Loc.GetString($"markings-organ-{region}"));
            index++;
        }

        if (index > 0)
            CategoryTabs.CurrentTab = 0;

        CategoryTabs.TabsVisible = index > 1;
    }

    private static readonly MarkingRegion[] RegionOrder =
    {
        MarkingRegion.Head,
        MarkingRegion.Torso,
        MarkingRegion.LeftArm,
        MarkingRegion.RightArm,
        MarkingRegion.LeftLeg,
        MarkingRegion.RightLeg,
        MarkingRegion.Tail,
        MarkingRegion.Special,
    };

    private Dictionary<MarkingRegion, List<MarkingLayerEntry>> BuildOrganData()
    {
        var result = new Dictionary<MarkingRegion, List<MarkingLayerEntry>>();

        foreach (var category in Enum.GetValues<MarkingCategories>())
        {
            if (_ignoredCategories.Contains(category))
                continue;

            var available = _model.GetAvailable(category, null);

            switch (category)
            {
                case MarkingCategories.Arms:
                    AddEntry(result, MarkingRegion.LeftArm, category, MarkingsViewModel.LeftArmLayers, available);
                    AddEntry(result, MarkingRegion.RightArm, category, MarkingsViewModel.RightArmLayers, available);
                    break;
                case MarkingCategories.Legs:
                    AddEntry(result, MarkingRegion.LeftLeg, category, MarkingsViewModel.LeftLegLayers, available);
                    AddEntry(result, MarkingRegion.RightLeg, category, MarkingsViewModel.RightLegLayers, available);
                    break;
                default:
                    AddEntry(result, MarkingsViewModel.RegionOf(category), category, null, available);
                    break;
            }
        }

        return result;
    }

    private void AddEntry(Dictionary<MarkingRegion, List<MarkingLayerEntry>> result,
        MarkingRegion region,
        MarkingCategories category,
        HashSet<HumanoidVisualLayers>? bodyParts,
        IReadOnlyDictionary<string, MarkingPrototype> available)
    {
        var hasAvailable = bodyParts == null
            ? available.Count > 0
            : available.Values.Any(prototype => bodyParts.Contains(prototype.BodyPart));

        var hasSelected = _model.SelectedMarkings(category, bodyParts) is { Count: > 0 };

        if (!hasAvailable && !hasSelected)
            return;

        if (!result.TryGetValue(region, out var layers))
        {
            layers = new List<MarkingLayerEntry>();
            result[region] = layers;
        }

        layers.Add(new MarkingLayerEntry(category, bodyParts));
    }

    private void RebuildIgnoredCategories()
    {
        _ignoredCategories.Clear();

        if (string.IsNullOrEmpty(_ignoreCategories))
            return;

        foreach (var part in _ignoreCategories.Split(',', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries))
        {
            foreach (var category in Enum.GetValues<MarkingCategories>())
            {
                if (string.Equals(category.ToString(), part, StringComparison.OrdinalIgnoreCase))
                {
                    _ignoredCategories.Add(category);
                    break;
                }
            }
        }
    }
}
